version: '3.5'

services:
  app:
    build: .
    volumes:
      - '.:/src'
    ports:
      - '3010:80'
    environment:
      - APP_DESCRIPTOR=dockerized
      - SERVER_PORT=80
      - ACME_CHALLENGE=B90U29t43br1xiFyu7N_hg1D3CcE8URCARc0bd2DgdA.AGorcgOrynTYzvtqIqRG3aBQj25JbmVr2nT3GhffRR4
